services:
   db:
      image: postgres:trixie
      container_name: postgres-5fruive
      restart: unless-stopped
      environment:
         POSTGRES_USER: ${DB_USER}
         POSTGRES_PASSWORD: ${DB_PASSWORD}
         POSTGRES_DB: ${DB_NAME}
      ports:
         - "5432:5432"
      volumes:
         - postgres-5fruive:/var/lib/postgresql
      profiles:
         - dev
      healthcheck:
         test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
         interval: 5s
         timeout: 5s
         retries: 5
   
   web:
      build:
         context: .
         dockerfile: Dockerfile
      depends_on:
         db:
            condition: service_healthy
      ports:
         - "8080:8080"
      environment:
         SPRING_PROFILES_ACTIVE: dev
         DB_URL: jdbc:postgresql://db:5432/fruive
         DB_USER: ${DB_USER}
         DB_PASSWORD: ${DB_PASSWORD}
      profiles:
         - dev
         
   web-ci:
      build:
         context: .
         dockerfile: Dockerfile.ci
      environment:
         SPRING_PROFILES_ACTIVE: test
      profiles:
         - ci

volumes:
   postgres-5fruive:
