services:
  db:
    image: postgres:trixie
    container_name: postgres-5fruive
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes: # please comment this and the line below on production environment
      - ./postgres_data:/var/lib/postgresql
