spring.application.name=majudge
spring.datasource.url=jdbc:h2:file:./majudge
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=gimmy
spring.datasource.password=mdpGimmy
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update